BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Temperature" (
	"TemperatureID"	INTEGER NOT NULL,
	"Datetime"	TEXT NOT NULL UNIQUE,
	"Temperature"	REAL NOT NULL,
	PRIMARY KEY("TemperatureID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Images" (
	"ImageID"	INTEGER NOT NULL,
	"Path"	TEXT NOT NULL,
	"Datetime"	TEXT NOT NULL,
	PRIMARY KEY("ImageID" AUTOINCREMENT)
);
COMMIT;
